<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>BeltSlot</RootNamespace>
      <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup>
    <Reference Include="Microsoft.CSharp">
      <HintPath>D:\ref4\Microsoft.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="PhysicsModule">
        <HintPath>D:\ref4\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
        <HintPath>D:\ref4\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="spt-common">
        <HintPath>D:\ref4\spt-common.dll</HintPath>
    </Reference>
    <Reference Include="spt-reflection">
        <HintPath>D:\ref4\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
        <HintPath>D:\ref4\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
        <HintPath>D:\ref4\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
        <HintPath>D:\ref4\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="Comfort.Unity, Version=1.0.0.4, Culture=neutral, processorArchitecture=MSIL">
        <SpecificVersion>False</SpecificVersion>
        <HintPath>D:\ref4\Comfort.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
        <SpecificVersion>False</SpecificVersion>
        <HintPath>D:\ref4\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
        <SpecificVersion>False</SpecificVersion>
        <HintPath>D:\ref4\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
        <SpecificVersion>False</SpecificVersion>
        <HintPath>D:\ref4\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
        <HintPath>D:\ref4\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
        <SpecificVersion>False</SpecificVersion>
        <HintPath>D:\ref4\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
        <HintPath>D:\ref4\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
        <SpecificVersion>False</SpecificVersion>
        <HintPath>D:\ref4\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
        <HintPath>D:\ref4\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
        <SpecificVersion>False</SpecificVersion>
        <HintPath>D:\ref4\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
        <SpecificVersion>False</SpecificVersion>
        <HintPath>D:\ref4\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="WTT-PackNStrap">
      <HintPath>D:\ref4\WTT-PackNStrap.dll</HintPath>
    </Reference>
</ItemGroup>

</Project>
